import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";

const path = ".env";

if (existsSync(path)) {
  console.log("dev:env: .env already exists; leaving it unchanged");
  const existing = await readFile(path, "utf8");
  const recommended = [
    "LLM_PROVIDER",
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_BASE_URL",
    "DEEPSEEK_CHAT_MODEL",
    "DEEPSEEK_REASONING_MODEL",
    "DEEPSEEK_TIMEOUT_MS",
    "DEEPSEEK_MAX_RETRIES",
    "DEEPSEEK_THINKING",
    "ANTHROPIC_MODEL",
    "VOICE_GATEWAY_ASR_PROVIDER",
    "BRAIN_ENABLED",
    "HUMAN_PROFILE_ENABLED",
    "STRESS_SUPPORT_ENABLED",
    "RESEARCH_PROVIDER",
    "TOOL_EXECUTION_MODE",
    "UPSTASH_REDIS_REST_URL",
    "UPSTASH_REDIS_REST_TOKEN",
  ].filter((key) => !new RegExp(`^${key}=`, "m").test(existing));
  if (recommended.length > 0) {
    console.log(`dev:env: missing recommended keys: ${recommended.join(", ")}`);
  }
} else {
  const jwtSecret = randomBytes(48).toString("base64url");
  const content = [
    "DATABASE_URL=postgres://gorkh:gorkh_dev_password@127.0.0.1:5432/gorkh_backend",
    "REDIS_URL=redis://127.0.0.1:6379",
    "UPSTASH_REDIS_REST_URL=",
    "UPSTASH_REDIS_REST_TOKEN=",
    "HOST=0.0.0.0",
    "PORT=3000",
    `JWT_SECRET=${jwtSecret}`,
    "LLM_PROVIDER=deepseek",
    "DEEPSEEK_API_KEY=",
    "DEEPSEEK_BASE_URL=https://api.deepseek.com",
    "DEEPSEEK_CHAT_MODEL=deepseek-v4-flash",
    "DEEPSEEK_REASONING_MODEL=deepseek-v4-pro",
    "DEEPSEEK_TIMEOUT_MS=15000",
    "DEEPSEEK_MAX_RETRIES=1",
    "DEEPSEEK_THINKING=disabled",
    "ANTHROPIC_MODEL=claude-3-5-sonnet-latest",
    "SUGGEST_MODEL=claude-3-5-sonnet-latest",
    "EXTRACT_MODEL=claude-3-5-sonnet-latest",
    "DEEPGRAM_MODEL=nova-3",
    "VOYAGE_MODEL=voyage-3-large",
    "VOYAGE_EMBED_DIM=1024",
    "CONTEXT_WINDOW_SEGMENTS=24",
    "SUGGESTION_COOLDOWN_MS=8000",
    "FAST_CUE_COOLDOWN_MS=5000",
    "VOICE_MAX_SPOKEN_WORDS=8",
    "VOICE_CUE_MIN_INTERVAL_MS=5000",
    "VOICE_AGENT_RESPONSE_MAX_CHARS=1200",
    "VOICE_DEFAULT_OUTPUT=text",
    "VOICE_TTS_PROVIDER=none",
    "VOICE_GATEWAY_HOST=0.0.0.0",
    "VOICE_GATEWAY_PORT=3010",
    "GORKH_BACKEND_HTTP_URL=http://127.0.0.1:3000",
    "GORKH_BACKEND_WS_URL=ws://127.0.0.1:3000",
    "VOICE_GATEWAY_ASR_PROVIDER=deepgram",
    "VOICE_GATEWAY_OUTPUT_STRATEGY=client_tts",
    "GATEWAY_MAX_PCM_FRAME_BYTES=64000",
    "GATEWAY_SESSION_IDLE_TIMEOUT_MS=120000",
    "GATEWAY_BACKEND_CONNECT_TIMEOUT_MS=10000",
    "BRAIN_ENABLED=true",
    "HUMAN_PROFILE_ENABLED=true",
    "HUMAN_PROFILE_REQUIRE_CONFIRMATION=true",
    "HUMAN_PROFILE_AUTO_SAVE_LOW_RISK=true",
    "HUMAN_PROFILE_AUTO_SAVE_SENSITIVE=false",
    "HUMAN_PROFILE_MAX_FACTS_PER_SESSION=12",
    "ADAPTIVE_LEARNING_ENABLED=true",
    "ADAPTIVE_SKILL_LEARNING_ENABLED=true",
    "ADAPTIVE_SKILL_AUTO_ENABLE=false",
    "ADAPTIVE_SKILL_REQUIRE_APPROVAL=true",
    "STRESS_SUPPORT_ENABLED=true",
    "STRESS_SUPPORT_REQUIRE_OPT_IN=true",
    "STRESS_SUPPORT_CRISIS_RESOURCES_ENABLED=true",
    "STRESS_SUPPORT_DEFAULT_LOCALE=FR",
    "STRESS_SUPPORT_FR_RESOURCE_NAME=3114",
    "STRESS_SUPPORT_FR_RESOURCE_DESCRIPTION=France national suicide prevention number, available 24/7",
    "STRESS_SUPPORT_US_RESOURCE_NAME=988",
    "STRESS_SUPPORT_US_RESOURCE_DESCRIPTION=US Suicide & Crisis Lifeline",
    "RESEARCH_PROVIDER=none",
    "BRAVE_API_KEY=",
    "TAVILY_API_KEY=",
    "EXA_API_KEY=",
    "RESEARCH_CACHE_TTL_SECONDS=900",
    "RESEARCH_MAX_RESULTS=6",
    "RESEARCH_MAX_FETCH_BYTES=500000",
    "RESEARCH_PROVIDER_TIMEOUT_MS=12000",
    "RESEARCH_TIMEOUT_MS=12000",
    "RESEARCH_REQUIRE_CITATIONS=true",
    "BROWSER_PROVIDER=none",
    "TOOL_EXECUTION_MODE=restricted",
    "SUBAGENTS_ENABLED=true",
    "SUBAGENT_RUNNER_MODE=db_worker",
    "SUBAGENT_WORKER_POLL_MS=1000",
    "SUBAGENT_WORKER_BATCH_SIZE=3",
    "SUBAGENT_TASK_LEASE_MS=30000",
    "SUBAGENT_TASK_HEARTBEAT_MS=5000",
    "SUBAGENT_MAX_CONCURRENCY=3",
    "SUBAGENT_DEFAULT_TIMEOUT_MS=15000",
    "SUBAGENT_RESEARCH_TIMEOUT_MS=20000",
    "SUBAGENT_DEFAULT_MAX_ATTEMPTS=3",
    "SUBAGENT_RETRY_BASE_MS=2000",
    "SUBAGENT_RETRY_MAX_MS=30000",
    "SUBAGENT_NOTIFICATION_RETENTION_HOURS=24",
    "SUBAGENT_REPORT_MAX_CHARS=2000",
    "SUBAGENT_LIVE_REPORT_SCREEN_ONLY=true",
    "",
  ].join("\n");
  await writeFile(path, content, { mode: 0o600 });
  console.log("dev:env: created .env with generated JWT_SECRET");
}
