import type { ConnectorManifest } from "./types.js";

export const connectorManifests: ConnectorManifest[] = [
  {
    id: "google_gmail",
    name: "Google Gmail",
    category: "email",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["read_email_headers", "draft_email", "send_email_requires_approval", "oauth_readonly_scope", "token_ref_required"],
    disabledReason: "OAuth connector is not implemented in v0. Draft proposals only.",
    riskLevel: "high",
  },
  {
    id: "google_calendar",
    name: "Google Calendar",
    category: "calendar",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["read_calendar", "propose_calendar_event", "create_calendar_event_requires_approval", "oauth_readonly_scope", "token_ref_required"],
    disabledReason: "OAuth connector is not implemented in v0. Calendar proposals only.",
    riskLevel: "high",
  },
  {
    id: "microsoft_outlook",
    name: "Microsoft Outlook",
    category: "email",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["read_email_headers", "read_email_body", "draft_email", "send_email_requires_approval", "read_calendar", "propose_calendar_event"],
    disabledReason: "OAuth connector is not implemented in v0.",
    riskLevel: "high",
  },
  {
    id: "notion",
    name: "Notion",
    category: "documents",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["read_documents", "write_documents_requires_approval"],
    disabledReason: "Connector is not configured in v0.",
    riskLevel: "medium",
  },
  {
    id: "slack",
    name: "Slack",
    category: "messaging",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["draft_email", "send_email_requires_approval"],
    disabledReason: "Messaging connector is not implemented in v0. No messages are sent.",
    riskLevel: "high",
  },
  {
    id: "todoist",
    name: "Todoist",
    category: "tasks",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["read_tasks", "create_task_requires_approval"],
    disabledReason: "Task connector is not implemented in v0. Use internal task inbox instead.",
    riskLevel: "medium",
  },
  {
    id: "github",
    name: "GitHub",
    category: "code",
    enabled: false,
    configured: false,
    authType: "oauth_placeholder",
    permissions: ["read_documents", "write_documents_requires_approval"],
    disabledReason: "GitHub connector is not implemented in v0.",
    riskLevel: "medium",
  },
  {
    id: "mcp_remote",
    name: "Remote MCP",
    category: "mcp",
    enabled: false,
    configured: false,
    authType: "none",
    permissions: ["mcp_tool_invoke_requires_manifest", "mcp_network_disabled_by_default"],
    disabledReason: "Remote MCP servers and arbitrary MCP tool execution are disabled in v0.",
    riskLevel: "high",
  },
];
