import SwiftUI

enum SettingsSection: String, CaseIterable {
    case accountToken = "Account / Token"
    case privacyData = "Privacy & Data"
    case audio = "Audio"
    case diagnostics = "Diagnostics"
    case developer = "Developer"
}

struct SettingsView: View {
    @EnvironmentObject private var appState: AppState
    @State private var token = ""
    @State private var statusMessage: String?
    @State private var microphoneStatus = SystemMicrophonePermissionProvider().currentStatus()

    var body: some View {
        Form {
            accountSection
            privacySection
            audioSection
            diagnosticsSection
            developerSection
        }
        .scrollContentBackground(.hidden)
        .background(NearMindTheme.background.ignoresSafeArea())
        .tint(NearMindTheme.accentMint)
        .navigationTitle("Settings")
        .navigationBarTitleDisplayMode(.inline)
        .onAppear {
            appState.refreshAuthStatus()
            microphoneStatus = SystemMicrophonePermissionProvider().currentStatus()
        }
    }

    private var accountSection: some View {
        Section(SettingsSection.accountToken.rawValue) {
            LabeledContent("Token status", value: tokenStatusText)

            SecureField("Paste test JWT", text: $token)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()

            Text("Paste a test JWT generated by the backend. NearMind stores it in Keychain only.")
                .font(.footnote)
                .foregroundStyle(.secondary)

            Button {
                saveToken()
            } label: {
                Label("Save token to Keychain", systemImage: "key")
            }
            .disabled(token.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)

            Button(role: .destructive) {
                clearToken()
            } label: {
                Label("Clear token", systemImage: "rectangle.portrait.and.arrow.right")
            }

            if let statusMessage {
                Text(statusMessage)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
        }
        .listRowBackground(NearMindTheme.cardSurface)
    }

    private var privacySection: some View {
        Section(SettingsSection.privacyData.rawValue) {
            NavigationLink {
                PrivacyDataSettingsView()
            } label: {
                SettingsRow(title: "Privacy", subtitle: "Consent, stop, save, and discard behavior", systemImage: "lock.shield")
            }
            SettingsRow(title: "Token storage", subtitle: "JWTs stay in Keychain only", systemImage: "key.horizontal")
            SettingsRow(title: "Recording", subtitle: "No background or hidden microphone mode", systemImage: "mic.slash")
        }
        .listRowBackground(NearMindTheme.cardSurface)
    }

    private var audioSection: some View {
        Section(SettingsSection.audio.rawValue) {
            LabeledContent("Microphone", value: microphoneStatus.rawValue)
            Toggle(isOn: Binding(
                get: { appState.ttsMutedPreference },
                set: { appState.setTTSMutedPreference($0) }
            )) {
                SettingsRow(title: "Mute native TTS", subtitle: "Live Assist can still show text and cues", systemImage: "speaker.slash")
            }
            SettingsRow(title: "Output", subtitle: "Native iOS speech uses the current audio route", systemImage: "speaker.wave.2")
        }
        .listRowBackground(NearMindTheme.cardSurface)
    }

    private var diagnosticsSection: some View {
        Section(SettingsSection.diagnostics.rawValue) {
            NavigationLink {
                DiagnosticsSettingsView()
            } label: {
                SettingsRow(title: "Diagnostics", subtitle: "Backend endpoints, audio route notes, and logs", systemImage: "stethoscope")
            }
        }
        .listRowBackground(NearMindTheme.cardSurface)
    }

    private var developerSection: some View {
        Section(SettingsSection.developer.rawValue) {
            NavigationLink {
                DeveloperSettingsView()
            } label: {
                SettingsRow(title: "Developer tools", subtitle: "Typed smoke test and raw event log", systemImage: "hammer")
            }
        }
        .listRowBackground(NearMindTheme.cardSurface)
    }

    private func saveToken() {
        do {
            try appState.environment.tokenStore.saveToken(token.trimmingCharacters(in: .whitespacesAndNewlines))
            token = ""
            statusMessage = "Token saved."
            appState.refreshAuthStatus()
        } catch {
            statusMessage = error.localizedDescription
        }
    }

    private func clearToken() {
        do {
            try appState.environment.tokenStore.clearToken()
            statusMessage = "Token cleared."
            appState.refreshAuthStatus()
        } catch {
            statusMessage = error.localizedDescription
        }
    }

    private var tokenStatusText: String {
        switch appState.tokenStatus {
        case .missing:
            return "missing"
        case .stored:
            return "stored"
        case .invalid:
            return "invalid"
        }
    }
}

private struct SettingsRow: View {
    let title: String
    let subtitle: String
    let systemImage: String

    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: systemImage)
                .foregroundStyle(NearMindTheme.accentMint)
                .frame(width: 24)
            VStack(alignment: .leading, spacing: 3) {
                Text(title)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(NearMindTheme.textPrimary)
                Text(subtitle)
                    .font(.caption)
                    .foregroundStyle(NearMindTheme.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .padding(.vertical, 2)
    }
}

private struct PrivacyDataSettingsView: View {
    var body: some View {
        List {
            Section("Privacy posture") {
                SettingsRow(title: "Consent-first", subtitle: "Live Assist starts only after you opt in for a session.", systemImage: "hand.raised")
                SettingsRow(title: "Session control", subtitle: "Stop with save=false to discard session retention.", systemImage: "xmark.circle")
                SettingsRow(title: "Credential handling", subtitle: "Test JWTs are stored in Keychain and never shown in logs.", systemImage: "lock")
            }
        }
        .scrollContentBackground(.hidden)
        .background(NearMindTheme.background.ignoresSafeArea())
        .navigationTitle("Privacy")
        .navigationBarTitleDisplayMode(.inline)
    }
}

private struct DiagnosticsSettingsView: View {
    @EnvironmentObject private var appState: AppState

    var body: some View {
        List {
            Section("Backend") {
                LabeledContent("API", value: appState.environment.config.apiBaseURL.absoluteString)
                LabeledContent("Gateway", value: appState.environment.config.gatewayWebSocketURL.absoluteString)
                LabeledContent("Gateway HTTP", value: appState.environment.config.gatewayHTTPURL.absoluteString)
            }

            Section("App") {
                LabeledContent("Version", value: Bundle.main.shortVersionString)
                LabeledContent("Build", value: Bundle.main.buildNumber)
            }

            Section("Logs") {
                NavigationLink {
                    DebugEventLogView()
                } label: {
                    SettingsRow(title: "Debug event log", subtitle: "Token and raw audio payloads are not logged.", systemImage: "doc.text.magnifyingglass")
                }
            }
        }
        .scrollContentBackground(.hidden)
        .background(NearMindTheme.background.ignoresSafeArea())
        .navigationTitle("Diagnostics")
        .navigationBarTitleDisplayMode(.inline)
    }
}

private struct DeveloperSettingsView: View {
    var body: some View {
        List {
            Section("Smoke testing") {
                NavigationLink {
                    LiveSmokeView()
                } label: {
                    SettingsRow(title: "Typed Live Smoke", subtitle: "Gateway protocol test without microphone.", systemImage: "keyboard")
                }
            }

            Section("Policy") {
                SettingsRow(title: "No provider secrets", subtitle: "Provider keys and API secrets do not belong in the app.", systemImage: "exclamationmark.shield")
                SettingsRow(title: "No userId payloads", subtitle: "Client messages continue to omit userId.", systemImage: "person.crop.circle.badge.xmark")
            }
        }
        .scrollContentBackground(.hidden)
        .background(NearMindTheme.background.ignoresSafeArea())
        .navigationTitle("Developer")
        .navigationBarTitleDisplayMode(.inline)
    }
}

private extension Bundle {
    var shortVersionString: String {
        object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "0.1"
    }

    var buildNumber: String {
        object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "local"
    }
}
